name: "Terraform Provision AWS EKS Cluster with Snyk Scan"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Provision AWS Infrastructure"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Install Snyk CLI
      run: |
        curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x snyk
        sudo mv snyk /usr/local/bin/

    - name: Snyk Scan Terraform Files
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk iac test --severity-threshold=high --scan=resource terraform/

    - name: Terraform Apply
      if: success()
      run: terraform apply -auto-approve tfplan
